#!/usr/bin/env python3
"""Answers the build's questions from updater.cfg.

  updater_cfg.py kernel     yes or no: build the updater into BMC64
  updater_cfg.py webui      yes or no: include the Web UI's Update page
  updater_cfg.py repo       the GitHub repository (owner/name), or nothing
  updater_cfg.py webui-js   write src/webui/assets/update/settings.js

updater.cfg sets updater = on (kernel and webui), kernel_only (kernel) or
off (neither). No updater.cfg is the same as off.
"""

import argparse
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
DEFAULT_CFG = os.path.join(REPO_ROOT, "updater.cfg")
DEFAULT_WEBUI_JS = os.path.join(REPO_ROOT, "src", "webui", "assets", "update",
                                "settings.js")

# updater = ... -> (kernel, webui)
MODES = {"on": (True, True), "kernel_only": (True, False), "off": (False, False)}


def load(path=DEFAULT_CFG):
    """{"kernel": bool, "webui": bool, "repo": str}."""
    mode, repo = "off", ""
    if os.path.exists(path):
        with open(path) as f:
            for number, raw in enumerate(f, 1):
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                key, sep, value = line.partition("=")
                key, value = key.strip().lower(), value.strip()
                if sep and key == "updater" and value.lower() in MODES:
                    mode = value.lower()
                elif sep and key == "repo" and (not value or
                                                (value.count("/") == 1 and " " not in value)):
                    repo = value
                else:
                    sys.exit("%s:%d: expected updater = on, kernel_only or off, "
                             "or repo = owner/name" % (path, number))
    kernel, webui = MODES[mode]
    return {"kernel": kernel, "webui": webui, "repo": repo}


def write_webui_js(settings, js_path=DEFAULT_WEBUI_JS):
    """Writes the Web UI's copy of the settings; only if it changed."""
    text = (
        "// The updater settings from updater.cfg. Generated by\n"
        "// tools/update/updater_cfg.py (the Web UI build runs it); do not edit.\n"
        "\n"
        "export const UPDATER = { enabled: %s, repo: \"%s\" };\n"
        % ("true" if settings["webui"] else "false", settings["repo"]))
    if os.path.exists(js_path):
        with open(js_path) as f:
            if f.read() == text:
                return
    with open(js_path, "w", newline="\n") as f:
        f.write(text)
    print("wrote %s" % os.path.relpath(js_path, REPO_ROOT))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("what", choices=["kernel", "webui", "repo", "webui-js"])
    ap.add_argument("--cfg", default=DEFAULT_CFG)
    ap.add_argument("--out", default=DEFAULT_WEBUI_JS, help="for webui-js")
    opts = ap.parse_args()

    settings = load(opts.cfg)
    if opts.what == "webui-js":
        write_webui_js(settings, opts.out)
    elif opts.what == "repo":
        print(settings["repo"])
    else:
        print("yes" if settings[opts.what] else "no")


if __name__ == "__main__":
    main()
