// Reference data for basic.test.js. Generated by gen_basic_vectors.py; do not edit.

// Expected PRG bytes (hex) for each listing, from VICE's petcat (after the
// listing is put in the form a real C64 would store it).
export const GOLDEN = [
 {
  "name": "print and goto",
  "listing": "10 print \"hello\"\n20 goto 10\n",
  "hex": "01080f080a0099202248454c4c4f22001808140089203130000000"
 },
 {
  "name": "mixed case text",
  "listing": "10 print \"Hello World\"\n",
  "hex": "010815080a0099202248454c4c4f20574f524c4422000000"
 },
 {
  "name": "operators and tokens after then",
  "listing": "10 x=total>=3:if a<>b then print\"x\":go to 10\n",
  "hex": "010824080a0058b2a454414cb1b2333a8b2041b3b14220a720992258223acb20a4203130000000"
 },
 {
  "name": "data and rem are not tokenised",
  "listing": "10 data 1,2,print,\"a:b\":rem print here\n20 data print:print \"x\"\n",
  "hex": "010824080a008320312c322c5052494e542c22413a42223a8f205052494e542048455245003608140083205052494e543a9920225822000000"
 },
 {
  "name": "for next gosub",
  "listing": "10 for i=1 to 10 step 2:next i\n30 gosub 100:return\n",
  "hex": "010818080a00812049b23120a420313020a920323a8220490024081e008d203130303a8e000000"
 },
 {
  "name": "file commands",
  "listing": "10 open 1,8,15,\"s0:x\":print#1,\"a\":input#1,a$:close 1\n",
  "hex": "010826080a009f20312c382c31352c2253303a58223a98312c2241223a84312c41243aa02031000000"
 },
 {
  "name": "poke sys peek and or",
  "listing": "10 poke 53280,0:sys 49152:x=peek(1)and 3 or 4\n",
  "hex": "010825080a00972035333238302c303a9e2034393135323a58b2c2283129af203320b02034000000"
 },
 {
  "name": "string functions",
  "listing": "10 a$=left$(b$,3)+mid$(c$,2,1)+right$(d$,1)+str$(1)+chr$(65)\n",
  "hex": "01082d080a004124b2c82842242c3329aaca2843242c322c3129aac92844242c3129aac4283129aac728363529000000"
 },
 {
  "name": "tab spc fn on goto",
  "listing": "10 tab(5)spc(3)fn a(x)\n20 on x goto 1,2,3\n",
  "hex": "010812080a00a33529a63329a520412858290022081400912058208920312c322c33000000"
 },
 {
  "name": "rem and data edge cases",
  "listing": "10 rem\n20 rem :::\n30 dataa\n",
  "hex": "010807080a008f00110814008f203a3a3a0018081e008341000000"
 },
 {
  "name": "unclosed and doubled quotes",
  "listing": "10 print \"unclosed\n20 print \"a\"b\"c\"\n",
  "hex": "010811080a00992022554e434c4f534544001f081400992022412242224322000000"
 },
 {
  "name": "keywords inside variable names",
  "listing": "10 orders=1:format=2:gotox=3:total=4\n",
  "hex": "010820080a00b044455253b2313a814d4154b2323a8958b2333aa454414cb234000000"
 },
 {
  "name": "lines are sorted, a repeated number replaces",
  "listing": "30 print 3\n10 print 1\n20 print 2\n10 print 99\n",
  "hex": "01080a080a00992039390012081400992032001a081e00992033000000"
 },
 {
  "name": "a bare line number deletes the line",
  "listing": "10 print 1\n20 print 2\n20\n",
  "hex": "010809080a00992031000000"
 },
 {
  "name": "? is PRINT",
  "listing": "10 ?\"x\":?chr$(1)\n",
  "hex": "010810080a00992258223a99c7283129000000"
 },
 {
  "name": "a repeated code in a string variable",
  "listing": "10 x$=\"{home}{right*39}{down*24}\"\n",
  "hex": "01084b080a005824b222131d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d11111111111111111111111111111111111111111111111122000000"
 },
 {
  "name": "a line that is only a colon",
  "listing": "10 print 1\n11 :\n12 print 2\n",
  "hex": "010809080a00992031000f080b003a0017080c00992032000000"
 },
 {
  "name": "a negative step in a for loop",
  "listing": "10 for i=7 to 0 step -1:next\n",
  "hex": "010816080a00812049b23720a4203020a920ab313a82000000"
 },
 {
  "name": "random 1",
  "listing": "10   rread sin\"f80\"\n",
  "hex": "01080f080a00528720bf2246383022000000"
 },
 {
  "name": "random 2",
  "listing": "10 2028\n20 <=:- \n",
  "hex": "01080a080a00323032380013081400b3b23aab000000"
 },
 {
  "name": "random 3",
  "listing": "10 wait<=poke\n20 >\">e9d;n4/\"\n30 soljpokecschr$7353gotoexp\n40 pngotozkkwl\n50 $if  busv4662laolftread\n",
  "hex": "01080a080a0092b3b297001a081400b1223e4539443b4e342f22002d081e00534f4c4a974353c73733353389bd003a082800504e895a4b4b574c0052083200248b202042555356343636324c414f4c465487000000"
 },
 {
  "name": "random 4",
  "listing": "10 xh\"fk1z8ri\"9014exp\n",
  "hex": "010816080a00584822464b315a3852492239303134bd000000"
 },
 {
  "name": "random 5",
  "listing": "10 hecfcmdpokeendusr,\n20 tuvxb\")/%8zzzzg3+z\"let\n",
  "hex": "01080f080a00484543469d9780b72c0028081400545556584222292f25385a5a5a5a47332b5a2288000000"
 },
 {
  "name": "random 6",
  "listing": "10 \"v\"/load;\n20 cont\n30 close:\"h\"7634\"fjg?\"get\"k6bn6xj<7b!\"\n40  qlf\"77#\"=>\n50 3714chr$\"\"  \n",
  "hex": "01080c080a00225622ad933b00120814009a0034081e00a03a2248223736333422464a473f22a1224b36424e36584a3c374221220043082800514c462237372322b2b1004f08320033373134c72222000000"
 },
 {
  "name": "random 7",
  "listing": "10 sgn\"wxfogo3mvn3\"+\"w%-f'*hy$>\"fnzusqr\"f=kkibj:2%-\"str$\n",
  "hex": "010833080a00b4225758464f474f334d564e3322aa2257252d46272a4859243e22a55a55ba22463d4b4b49424a3a32252d22c4000000"
 },
 {
  "name": "random 8",
  "listing": "10 stopgosub^\"&)n\"listsys\n20 exp997  95578466\"i7j65b)1\"\n",
  "hex": "010810080a00908dae2226294e229b9e002d081400bd393937202039353537383436362249374a363542293122000000"
 },
 {
  "name": "random 9",
  "listing": "10 ^str$/\n20 mid$\n30 rprint#restore>=let\"5,5m<r157\"8319:\n40  2246\"1ue*p0\"spc(wu\n50 on m2667 sin\n",
  "hex": "010809080a00aec4ad000f081400ca002a081e0052988cb1b28822352c354d3c5231353722383331393a003e08280032323436223155452a503022a65755004c08320091204d3236363720bf000000"
 },
 {
  "name": "random 10",
  "listing": "10 print\"=\"\"821>b\"\";s5eh$og\"newpokestop\n",
  "hex": "01081e080a0099223d22223832313e4222223b53354548244f4722a29790000000"
 },
 {
  "name": "random 11",
  "listing": "10 4237\"594<ufrd\"ncnext(clrrem\n20 exp  -= pokethen<>\n",
  "hex": "01081a080a0034323337223539343c55465244224e4382289c8f0029081400bd2020abb22097a7b3b1000000"
 },
 {
  "name": "random 12",
  "listing": "10 left$lza left$\n20 = nvprmqlist\n30 on\"d'iae\"(\"\"\n40 qvjtfn\n50 \"r1\"\n",
  "hex": "01080c080a00c84c5a4120c8001a081400b2204e5650524d519b002a081e009122442749414522282222003408280051564a54a5003d08320022523122000000"
 },
 {
  "name": "random 13",
  "listing": "10 and\n",
  "hex": "010807080a00af000000"
 },
 {
  "name": "random 14",
  "listing": "10 thenpokefretab(>end\n20 ifinput\n",
  "hex": "01080c080a00a797b8a3b18000130814008b85000000"
 },
 {
  "name": "random 15",
  "listing": "10 spc(*<>2543ztmykx wait\n20 8404\n30 eqyqs2639569vwuhcaabs  9150\n40 >=\n50 \"\"\"?\":go\n",
  "hex": "010816080a00a6acb3b1323534335a544d594b582092001f08140038343034003d081e00455159515332363339353639565755484341b62020393135300044082800b1b200500832002222223f223acb000000"
 },
 {
  "name": "random 16",
  "listing": "10 izcicont\n",
  "hex": "01080b080a00495a43499a000000"
 },
 {
  "name": "random 17",
  "listing": "10 pmcp  uugctclose\n20 ^read\"g<n/4s>6s2\"\"h8mtf3bs2e&5\"  \n",
  "hex": "010812080a00504d435020205555474354a00033081400ae8722473c4e2f34533e365332222248384d54463342533245263522000000"
 },
 {
  "name": "random 18",
  "listing": "10 \"e:f\"goabsright$return\n20 asc\"a4\"jxennotandor\n30 printjilcmm:cosito^\n40   >azyu\"8n=fd= 1\"\n50 )\"ik3 vstq\"imuhjp\n",
  "hex": "01080f080a0022453a4622cbb6c98e0020081400c6224134224a58454ea8afb00031081e00994a494c434d4d3abe49a4ae0045082800b1415a595522384e3d46443d203122005b0832002922494b33205653545122494d55484a50000000"
 },
 {
  "name": "random 19",
  "listing": "10 saveleft$  $  \"mpflv8fu\"get\n",
  "hex": "010818080a0094c82020242020224d50464c5638465522a1000000"
 },
 {
  "name": "random 20",
  "listing": "10 6763\"6nyrv!d4r9x\"left$>\n20 open\"10t(&)bic0\"\n",
  "hex": "010819080a003637363322364e59525621443452395822c8b1002b0814009f223130542826294249433022000000"
 },
 {
  "name": "random 21",
  "listing": "10   sqr:7355gosubload/:\n20 inputstopinput#):sindgo\n30 \"$,a\"spc(  :\n40 \"8pb\":-chr$\n50 cmdhpbnlvmgaqcgpgjhofnchr$\n",
  "hex": "010810080a00ba3a373335358d93ad3a001d081400859084293abf44cb002b081e0022242c4122a620203a003808280022385042223aabc700510832009d4850424e4c564d474151434750474a484fa5c7000000"
 },
 {
  "name": "random 22",
  "listing": "10 7947\"d,jzdnb,j \"read\n",
  "hex": "010817080a003739343722442c4a5a444e422c4a202287000000"
 },
 {
  "name": "random 23",
  "listing": "10 \"u=hfkvml-6?\"\"*=y'\"\"1kgaf\"\n20 exp >\"&t&%0fd>3mx7\" \n",
  "hex": "010820080a0022553d48464b564d4c2d363f22222a3d59272222314b474146220036081400bd20b122265426253046443e334d583722000000"
 },
 {
  "name": "random 24",
  "listing": "10 \"b+ p%+#\"\"c2e%dq\"let5555\";cq?>\"jax\n20 cmdlen\n30 pepfspc(2479,7549\",f5mz!kp e-c\"\"uk0geq;f\"\n40 chr$  on\"/p?7(#*!h\"\n50 new\"qm1plppjs:m\"sqropen=\n",
  "hex": "010826080a0022422b2050252b232222433245254451228835353535223b43513f3e224a4158002d0814009dc30058081e0050455046a6323437392c37353439222c46354d5a214b5020452d432222554b304745513b4622006c082800c7202091222f503f3728232a2148220082083200a222514d31504c50504a533a4d22ba9fb2000000"
 },
 {
  "name": "random 25",
  "listing": "10 dcmd\n",
  "hex": "010808080a00449d000000"
 },
 {
  "name": "random 26",
  "listing": "10  3815print#<=goto\"1,\"endsgn\n20 orcont >\n",
  "hex": "010814080a003338313598b3b28922312c2280b4001d081400b09a20b1000000"
 },
 {
  "name": "random 27",
  "listing": "10 6700\n20 theninput#pcndz\"j+7f-kz<\"tobjxs\n30 \"\"5960:an  if\n40 ;\"ia\"wait:usrelmid$\n50  \"%$%mti'c3ud,\"  \n",
  "hex": "01080a080a00363730300025081400a78450434e445a224a2b37462d4b5a3c22a4424a58530036081e002222353936303a414e20208b00460828003b22494122923ab7454cca0059083200222524254d544927433355442c22000000"
 },
 {
  "name": "random 28",
  "listing": "10 :uz\n",
  "hex": "010809080a003a555a000000"
 },
 {
  "name": "random 29",
  "listing": "10 >2997-\"kywhjp=&\"\n20 input#dmt\"#t- t:p0y*\"\"1lba;42p\"\n",
  "hex": "010816080a00b132393937ab224b5957484a503d2622003508140084444d542223542d20543a5030592a2222314c42413b34325022000000"
 },
 {
  "name": "random 30",
  "listing": "10 fzpmstop\"f%155\"unotcbyqmac:\n20 ascverify\n30 sgn(tab(  \n40 valget=\n50 \"lzk\"(fzzigoabs  \n",
  "hex": "01081c080a00465a504d902246253135352255a8434259514d41433a0023081400c695002b081e00b428a30033082800c5a1b20044083200224c5a4b2228465a5a49cbb6000000"
 }
];

// The keywords of the C64 BASIC ROM, in token order from $80 (its own table at $A09E).
export const ROM_KEYWORDS = ["END", "FOR", "NEXT", "DATA", "INPUT#", "INPUT", "DIM", "READ", "LET", "GOTO", "RUN", "IF", "RESTORE", "GOSUB", "RETURN", "REM", "STOP", "ON", "WAIT", "LOAD", "SAVE", "VERIFY", "DEF", "POKE", "PRINT#", "PRINT", "CONT", "LIST", "CLR", "CMD", "SYS", "OPEN", "CLOSE", "GET", "NEW", "TAB(", "TO", "FN", "SPC(", "THEN", "NOT", "STEP", "+", "-", "*", "/", "^", "AND", "OR", ">", "=", "<", "SGN", "INT", "ABS", "USR", "FRE", "POS", "SQR", "RND", "LOG", "EXP", "COS", "SIN", "TAN", "ATN", "PEEK", "LEN", "STR$", "VAL", "ASC", "CHR$", "LEFT$", "RIGHT$", "MID$", "GO"];
