#!/usr/bin/env python3
"""Embed the BMC64 web UI static assets into a C source file.

Reads every file under src/webui/assets/ (including subfolders such as js/)
and writes src/webui/webui_assets.c,
which is compiled into the kernel image. Run this after editing any asset:

    python3 tools/gen_webui_assets.py

The generated file is checked in so a normal build needs no extra tooling.
"""

import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(REPO_ROOT, "src", "webui", "assets")
OUT_FILE = os.path.join(REPO_ROOT, "src", "webui", "webui_assets.c")

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


def request_paths(relpath):
    """HTTP request paths that should resolve to this asset."""
    if relpath == "index.html":
        return ["/", "/index.html"]
    return ["/" + relpath]


def list_assets():
    """Asset paths relative to ASSET_DIR, with '/' separators, sorted."""
    found = []
    for folder, _dirs, names in os.walk(ASSET_DIR):
        for name in names:
            rel = os.path.relpath(os.path.join(folder, name), ASSET_DIR)
            found.append(rel.replace(os.sep, "/"))
    return sorted(found)


def main():
    if not os.path.isdir(ASSET_DIR):
        sys.exit("asset directory not found: " + ASSET_DIR)

    # The Update page's built-in list of official releases is generated from
    # release/release_digests.txt; refresh it before embedding the assets.
    subprocess.run([sys.executable,
                    os.path.join(REPO_ROOT, "tools", "update", "gen_update_manifest.py"),
                    "webui"], check=True)

    files = list_assets()
    if not files:
        sys.exit("no assets found in " + ASSET_DIR)

    blobs = []
    table = []
    for index, name in enumerate(files):
        ext = os.path.splitext(name)[1].lower()
        ctype = CONTENT_TYPES.get(ext, "application/octet-stream")
        with open(os.path.join(ASSET_DIR, *name.split("/")), "rb") as fh:
            data = fh.read()

        lines = []
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            lines.append("  " + "".join("0x%02x, " % b for b in chunk).rstrip())
        blobs.append(
            "static const unsigned char asset_%d[] = {\n%s\n};\n"
            % (index, "\n".join(lines) if lines else "  0x00"))

        for path in request_paths(name):
            table.append(
                '  { "%s", "%s", asset_%d, %d },'
                % (path, ctype, index, len(data)))

    with open(OUT_FILE, "w") as out:
        out.write("// Generated by tools/gen_webui_assets.py - do not edit.\n")
        out.write("// Source files live in src/webui/assets/.\n\n")
        out.write('#include "webui_assets.h"\n\n')
        out.write("\n".join(blobs))
        out.write("\nconst struct webui_asset g_webui_assets[] = {\n")
        out.write("\n".join(table))
        out.write("\n};\n\n")
        out.write("const unsigned int g_webui_asset_count =\n")
        out.write("    sizeof(g_webui_assets) / sizeof(g_webui_assets[0]);\n")

    total = sum(os.path.getsize(os.path.join(ASSET_DIR, *n.split("/")))
                for n in files)
    print("wrote %s (%d files, %d bytes)" % (
        os.path.relpath(OUT_FILE, REPO_ROOT), len(files), total))


if __name__ == "__main__":
    main()
